name: example
description: A web server built using the shelf package.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  json_sorter:
    path: ../.
  shelf: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
